### ISSUE TITLE
Visual Studio support

### ISSUE THREAD

**Issue by bart9h** [viaduck/openssl-cmake#11]
Looks like mingw is the only option for now..

My project builds on Visual Studio for the Windows version.

Is it possible to support it?

**Comment by samuelh2005** [comment]
Works for me using vs2022

**Comment by roussosalex** [comment]
Could you provide some details as to what does not work for you, @bart9h? We do not plan on supporting VS ourselves, but we are open to PRs.

**Comment by bart9h** [comment]
I ended up using another solution, sorry.  (At least for now..)
