### ISSUE TITLE
Dylib search paths on macOS

### ISSUE THREAD

**Issue by pr0g** [viaduck/openssl-cmake#14]
I've been playing around with `openssl-cmake` lately and it's been very helpful so far. One issue I've run into unfortunately is dylib search paths, and I wanted to ask if you knew of a better way to solve this particular problem.

Right now, when I build using `openssl-cmake`, the libraries that get produced have the locations of the shared libraries they use set to `/usr/local/lib/`. Here's an example below:

```bash
❯ otool -L libssl.3.dylib     
libssl.3.dylib:
	/usr/local/lib/libssl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/local/lib/libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.0.0)
```

As the files aren't actually located there (`libssl.3.dylib` and `libcrypto.3.dylib`), I found I would get errors when running my application with the libraries failing to be located and loaded.

To work around this I can manually use `install_name_tool` and replace the paths with `@rpath` versions, so the above becomes:

```bash
❯ otool -L libssl.3.dylib   
libssl.3.dylib:
	@rpath/libssl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	@rpath/libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.0.0)
```

After running...

```bash
install_name_tool -id "@rpath/libssl.3.dylib" libssl.3.dylib
install_name_tool -change "/usr/local/lib/libcrypto.3.dylib" "@rpath/libcrypto.3.dylib" libssl.3.dylib
```

For now, I've just bundled the above options into a `.sh` file that I run using a CMake custom command:

```cmake
if(APPLE)
  add_custom_command(
    TARGET <my target that needs to link>
    POST_BUILD
    COMMAND <path/to>/rpath-fixup.sh
    WORKING_DIRECTORY <path/to/working/directory>
    COMMENT "Fixing-up rpaths...")
endif()
```

This does technically solve my problem, but it would be nice if I could fix this in the `CMakeLists.txt` files in this repo. I unfortunately haven't had much luck though. I believe as the targets are `IMPORTED`, it's not possible to update/modify them (so all the stuff todo with [rpaths in CMake](https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling) doesn't seem to work).

If you have any ideas on how to resolve this I'd be very grateful to know. If there isn't a CMake native solution I can stick with my approach for now.

Thanks very much for your time!

**Comment by roussosalex** [comment]
Thanks for reporting! We recently fixed some of the issues you described in this issue as well as in #15 in the v3 branch, e.g. install support, patching older versions and RPATH handling.  You could now set `OPENSSL_RPATH="$ORIGIN"`.

**Comment by pr0g** [comment]
Thanks for the update @roussosalex, I'll check out the V3 branch in the next little while. The workaround I mentioned has been working well so far but building is relatively slow. I'm curious if you've done any measurements of the build time improvements of OpenSSL-CMake if using Ninja? Thanks!

**Comment by roussosalex** [comment]
Since building OpenSSL internally must always use make (for now), switching to ninja in openssl-cmake would not make a noticeable difference.

**Comment by pr0g** [comment]
I see got you, thanks for the info 👍
