### ISSUE TITLE
Unable to build on Windows using Visual Studio

### ISSUE THREAD

**Issue by naushadck** [viaduck/openssl-cmake#16]
Tried to build openssl in windos 10 ith visual studio 2022. But no output or the library was build. 

Steps followed.

1. Openssl downloaded from git and extracted in a folder. 
2. Copied the contents from https://github.com/viaduck/openssl-cmake
3. created a subfolder "build"
4. cd build
5. cmake .. 

The above generated the visual studio solution(.sln) and related files. 
Tried to build using the .sln file. But no .exe/.dll was generated. 

Any support is highly appreciated.

**Comment by roussosalex** [comment]
@naushadck This project requires a unix-like environment to build OpenSSL. On Windows, you will need MSYS2/mingw-w64 (see [this part](/viaduck/openssl-cmake/blob/v3/cmake/BuildOpenSSL.cmake#L60) of the build script for details).
