### ISSUE TITLE
How to use the prebuilt binary in gradle project ?

### ISSUE THREAD

**Issue by dimaslanjaka** [viaduck/openssl-cmake#17]
Because of https://github.com/viaduck/openssl-cmake/issues/16 I cannot build openssl from source, so can you add documentation how to use the prebuilt ?

i want bind openssl and crypto to my cpp.

```cmake
add_library(native-lib SHARED main/cpp/native-lib.cpp)

target_link_libraries(native-lib crypto ssl android log)
```

**Comment by roussosalex** [comment]
Why can you not build OpenSSL for Android? #16 only covers Windows with MSVC, not building on Windows in general.

Also, using the prebuilts does not need any extra documentation, because they are pulled by default with no configuration required. Just link `crypto` and `ssl` as you did.
