### ISSUE TITLE
Prebuilt DLL files are in the wrong directory on windows?

### ISSUE THREAD

**Issue by jonas-s-s-s** [viaduck/openssl-cmake#18]
I have added this respository as a submodule and linked one of my targets against ssl and crypto. The issue is that my exe is in `./cmake-build-debug/src/main.exe` while the required DLLs are in `./cmake-build-debug/external/openssl-cmake/openssl-prefix/src/openssl/usr/local/bin/ `. Which causes the executable to crash as it cannot find these libraries. 

So I always have to either copy them manually to the  `./cmake-build-debug/src/` directory or use a copy command inside my cmake script. I think there should be something to do this automatically or at least add a warning about this into the usage section so other people don't have to wonder why they're getting exit code 0xC0000135?

**Comment by roussosalex** [comment]
Could you provide some information regarding your build system, e.g. which compiler and toolchain you are using? Also, have you tried the cmake install command?

**Comment by jonas-s-s-s** [comment]
This was on MinGW 1120_64, CMake 3.27. I tried several install commands but none worked, maybe it was some issue related to that. Anyway I ended up using static linking as it was more reliable than this.
