### ISSUE TITLE
Path to prebuilds change?

### ISSUE THREAD

**Issue by rcarlisle-spyrus** [viaduck/openssl-cmake#2]
Did the path to the prebuilts change?  cmake builds failing now with failure to download prebuilts at this path:

downloading 'https://mirror.viaduck.org/prebuilts/openssl/x86_64-android.tar.gz' failed |  
-- | --

**Comment by roussosalex** [comment]
Yes you are right. Just pushed the correct commits, so it should work now.

**Comment by rcarlisle-spyrus** [comment]
all fixed, thank you!!
