### ISSUE TITLE
Git global config changes clash during parallel builds

### ISSUE THREAD

**Issue by Marandil** [viaduck/openssl-cmake#21]
In cmake/BuildOpenSSL.cmake the following ExternalProject steps are added:
* setGitConfig
* restoreGitConfig

When running multiple builds in parallel it's common many of them fail, caused by a lock/race condition on access to ~/.gitconfig.
Given source is pulled as tarball from mirror instead of git, the config steps are unnecessary.
Moreover, even when pulling from git, GIT_CONFIG on ExternalProject_Add should be used instead of touching global config.

Proposals:
1. Remove setGitConfig, restoreGitConfig and the associated logic
2. Still remove setGitConfig, restoreGitConfig and conditionally add GIT_CONFIG to ExternalProject_Add in case URL is replaced with GIT_REPOSITORY+GIT_TAG.

**Comment by roussosalex** [comment]
Thanks for contributing! The git configuration step really was a leftover artifact from an ancient era. We will remove it.
