### ISSUE TITLE
android  compile demo

### ISSUE THREAD

**Issue by zhuangsifei** [viaduck/openssl-cmake#5]
hello, could you show a complete android compile demo. There shows an error "Use NDK cmake toolchain or cmake android autoconfig" when I compile for Android

**Comment by kleest** [comment]
Have a look at the [CI configuration](https://github.com/viaduck/openssl-cmake/blob/master/.gitlab-ci.yml#L50-L60). You have to specify the path to the CMake toolchain file from the Android NDK installation, e.g. `-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake`. Android Studio does this automatically when [you setup linking to a native library](https://developer.android.com/studio/projects/gradle-external-native-builds.html).
