### ISSUE TITLE
Cannot use on windows

### ISSUE THREAD

**Issue by denisvlah** [viaduck/openssl-cmake#6]
When trying to configure cmake project it shows the following error:
Cannot find patch utility.  This is only required for Android
[cmake]   cross-compilation but due to script complexity the requirement is always
[cmake]   enforced.

Also the following cmake variables were set:
BUILD_OPENSSL ON
OPENSSL_BRANCH OpenSSL_1_1_1d
OPENSSL_BUILD_VERSION "1.1.1d"

**Comment by kleest** [comment]
You require the `patch` in your MinGW/MSYS installation. Maybe you could install it with the MinGW package manager (might be `mingw-get install msys-patch`?).

Note that using MSVC as compiler is not supported.
